CREATE TABLE agentes(
    cf INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	apellidos VARCHAR(255) NOT NULL,
	categoria VARCHAR(100)
);

CREATE TABLE turnos(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	agente INTEGER NOT NULL,
	fecha DATE NOT NULL,
	turno VARCHAR(10) NOT NULL,
	CONSTRAINT fk_turno_usuario FOREIGN KEY(id) REFERENCES usuarios(cf)
)